# Generated by Django 3.2.13 on 2022-04-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familles',
            options={},
        ),
        migrations.AlterModelTable(
            name='familles',
            table=None,
        ),
    ]
