# Generated by Django 3.2.13 on 2022-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220427_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='distinations',
            name='societe',
            field=models.CharField(blank=True, choices=[('argos', 'argos'), ('jupiter', 'jupiter'), ('ithaque', 'ithaque'), ('tanis', 'tanis')], default='0', max_length=50, null=True),
        ),
    ]
