# Generated by Django 3.2.13 on 2022-04-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_distinations_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinations',
            name='nom_dis',
            field=models.CharField(max_length=50),
        ),
    ]
