# Generated by Django 3.2.13 on 2022-04-30 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_distinations_nom_dis'),
    ]

    operations = [
        migrations.CreateModel(
            name='reparation_materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(blank=True, choices=[('1', 'en maintenance'), ('2', 'en marche'), ('3', 'deteruit'), ('4', 'en panne')], max_length=50, null=True)),
                ('observation', models.CharField(blank=True, max_length=250, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stock')),
                ('demander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.distinations')),
            ],
        ),
    ]
