# Generated by Django 3.2.13 on 2022-05-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_demande_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='validation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
