# Generated by Django 3.2.13 on 2022-05-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_reparation_materiel_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparation_materiel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
