# Generated by Django 3.2.13 on 2022-05-05 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_reparation_materiel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
