# Generated by Django 3.2.13 on 2022-05-05 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_task_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='follows',
            field=models.ManyToManyField(related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
