# Generated by Django 3.2.13 on 2022-05-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_task_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Description de tache'),
        ),
    ]
