# Generated by Django 3.2.13 on 2022-05-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(verbose_name='Description de tache'),
        ),
    ]
