# Generated by Django 3.2.13 on 2022-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinations',
            name='societe',
            field=models.CharField(blank=True, choices=[('argos', 'argos'), ('jupiter', 'jupiter'), ('ithaque', 'ithaque'), ('tanis', 'tanis'), ('autre', 'autre')], default='0', max_length=50, null=True),
        ),
    ]
