# Generated by Django 3.2.13 on 2022-05-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_distinations_societe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distinations',
            unique_together={('nom_dis', 'societe')},
        ),
    ]
