# Generated by Django 3.2.13 on 2022-05-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_distinations_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distinations',
            unique_together=set(),
        ),
    ]
