# Generated by Django 3.2.13 on 2022-05-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_distinations_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distinations',
            unique_together={('nom_dis', 'societe')},
        ),
    ]
