# Generated by Django 3.2.13 on 2022-05-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_distinations_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fournisseur',
            field=models.CharField(max_length=80),
        ),
    ]
