# Generated by Django 3.2.13 on 2022-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220530_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='validation',
            field=models.CharField(blank=True, choices=[('en-cours', 'en-cours'), ('rejeter', 'rejeter'), ('valider', 'valider')], max_length=50, null=True),
        ),
    ]
