# Generated by Django 3.2.13 on 2022-06-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_demande_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation_materiel',
            name='etat',
            field=models.CharField(blank=True, choices=[('en-maintenance', 'en-maintenance'), ('resolu', 'resolu'), ('en-panne', 'en-panne')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Demande_Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sousfamille', verbose_name='Article')),
                ('fournisseur', models.ManyToManyField(to='users.Contact', verbose_name='Fournisseur')),
            ],
        ),
    ]
