# Generated by Django 3.2.13 on 2022-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_demande_devis_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_devis',
            name='fournisseur',
            field=models.ManyToManyField(blank=True, to='users.Contact', verbose_name='Fournisseur'),
        ),
    ]
