# Generated by Django 3.2.13 on 2022-06-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_demande_devis_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_devis',
            name='avg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
