# Generated by Django 3.2.13 on 2022-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_demande_devis_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tel2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tel3',
        ),
        migrations.AddField(
            model_name='contact',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
