# Generated by Django 3.2.13 on 2022-06-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220622_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
