# Generated by Django 3.2.13 on 2022-07-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220623_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousfamille',
            name='icon',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
